---
name: Module-Depends
version: 0.13
author: []
abstract: identify the dependencies of a distribution
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Chained: 0
  File::Spec: 0
  YAML: 0
build_requires:
  Test::More: 0
provides:
  Module::Build:
    file: lib/Module/Depends/Intrusive.pm
    version: v54.54.54
  Module::Depends:
    file: lib/Module/Depends.pm
    version: 0.13
  Module::Depends::Intrusive:
    file: lib/Module/Depends/Intrusive.pm
  Module::Depends::Intrusive::Fake::Module::Build:
    file: lib/Module/Depends/Intrusive.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
