--- #YAML:1.0
name: Module-Depends
version: 0.02
author:
  - |-
    Richard Clamp, based on code extracted from the Fotango build system
    originally by James Duncan and Arthur Bergman.
abstract: identify the dependencies of a distribution
license: perl
requires:
  Class::Accessor::Chained: 0
  File::Spec: 0
  File::chdir: 0
  YAML: 0
recommends: {}
build_requires:
  Test::More: 0
conflicts: {}
provides:
  Module::Depends:
    file: lib/Module/Depends.pm
    version: 0.02
  Module::Depends::Intrusive:
    file: lib/Module/Depends/Intrusive.pm
  main:
    file: lib/Module/Depends/Intrusive.pm
generated_by: Module::Build version 0.22
